import { GameConfig, PredefinedResult, SymbolConfig, PaylineConfig } from '../../engine/types';

/**
 * Configuração do Jack Frost's Winter
 * Grid: Infinity Reels (começa 3x4, expande)
 * Tema: Inverno Mágico
 */

const SYMBOLS: SymbolConfig[] = [
  {
    id: 0,
    name: 'Symbol_0',
    displayName: 'Wild/Jack Frost',
    isWild: true,
    isScatter: false,
    payouts: [0, 0, 0, 0, 50, 100, 200, 400, 800],
  },
  {
    id: 1,
    name: 'Symbol_1',
    displayName: 'Scatter/Heart',
    isWild: false,
    isScatter: true,
    payouts: [0, 0, 0, 5, 10, 20, 50, 100, 200],
  },
  {
    id: 2,
    name: 'Symbol_2',
    displayName: 'Snowflake Purple',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 0, 20, 40, 80, 160, 320],
  },
  {
    id: 3,
    name: 'Symbol_3',
    displayName: 'Snowflake Blue',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 0, 15, 30, 60, 120, 240],
  },
  {
    id: 4,
    name: 'Symbol_4',
    displayName: 'Snowflake Teal',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 0, 10, 20, 40, 80, 160],
  },
  {
    id: 5,
    name: 'Symbol_5',
    displayName: 'Snowflake White',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 0, 8, 16, 32, 64, 128],
  },
  {
    id: 6,
    name: 'Symbol_6',
    displayName: 'Crystal A',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 0, 5, 10, 20, 40, 80],
  },
  {
    id: 7,
    name: 'Symbol_7',
    displayName: 'Crystal K',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 0, 5, 10, 20, 40, 80],
  },
  {
    id: 8,
    name: 'Symbol_8',
    displayName: 'Crystal Q',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 0, 4, 8, 16, 32, 64],
  },
  {
    id: 9,
    name: 'Symbol_9',
    displayName: 'Crystal J',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 0, 4, 8, 16, 32, 64],
  },
];

// Infinity Reels - posições para grid inicial 3x4
const PAYLINES: PaylineConfig[] = [
  { id: 0, name: 'Line 1', positions: [0, 1, 2] },
  { id: 1, name: 'Line 2', positions: [3, 4, 5] },
  { id: 2, name: 'Line 3', positions: [6, 7, 8] },
  { id: 3, name: 'Line 4', positions: [9, 10, 11] },
  { id: 4, name: 'Line 5', positions: [0, 4, 8] },
  { id: 5, name: 'Line 6', positions: [9, 4, 2] },
];

const PREDEFINED_WINS: PredefinedResult[] = [
  {
    icons: ['Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9'],
    activeIcons: [1, 2, 3, 4, 5],
    activeLines: [{
      index: 0,
      name: 'Symbol_2',
      combine: 5,
      way_243: 1,
      payout: 20,
      multiply: 0,
      win_amount: 4,
      active_icon: [1, 2, 3, 4, 5],
    }],
    dropLine: [],
    multiplyCount: 2,
    payout: 40,
  },
  {
    icons: ['Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9'],
    activeIcons: [1, 2, 3, 4, 5, 6],
    activeLines: [{
      index: 0,
      name: 'Symbol_3',
      combine: 6,
      way_243: 1,
      payout: 30,
      multiply: 0,
      win_amount: 6,
      active_icon: [1, 2, 3, 4, 5, 6],
    }],
    dropLine: [],
    multiplyCount: 3,
    payout: 90,
  },
  {
    icons: ['Symbol_4', 'Symbol_4', 'Symbol_4', 'Symbol_4', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_0', 'Symbol_1'],
    activeIcons: [1, 2, 3, 4, 5],
    activeLines: [{
      index: 0,
      name: 'Symbol_4',
      combine: 5,
      way_243: 1,
      payout: 10,
      multiply: 0,
      win_amount: 2,
      active_icon: [1, 2, 3, 4, 5],
    }],
    dropLine: [],
    multiplyCount: 2,
    payout: 20,
  },
  {
    icons: ['Symbol_5', 'Symbol_5', 'Symbol_5', 'Symbol_5', 'Symbol_5', 'Symbol_5', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_0'],
    activeIcons: [1, 2, 3, 4, 5, 6, 7],
    activeLines: [{
      index: 0,
      name: 'Symbol_5',
      combine: 7,
      way_243: 1,
      payout: 64,
      multiply: 0,
      win_amount: 12.8,
      active_icon: [1, 2, 3, 4, 5, 6, 7],
    }],
    dropLine: [],
    multiplyCount: 4,
    payout: 256,
  },
  {
    icons: ['Symbol_6', 'Symbol_6', 'Symbol_6', 'Symbol_6', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3'],
    activeIcons: [1, 2, 3, 4, 5],
    activeLines: [{
      index: 0,
      name: 'Symbol_6',
      combine: 5,
      way_243: 1,
      payout: 5,
      multiply: 0,
      win_amount: 1,
      active_icon: [1, 2, 3, 4, 5],
    }],
    dropLine: [],
    multiplyCount: 2,
    payout: 10,
  },
  // MEGAWIN
  {
    icons: ['Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4'],
    activeIcons: [1, 2, 3, 4, 5, 6, 7, 8],
    activeLines: [{
      index: 0,
      name: 'Symbol_0',
      combine: 8,
      way_243: 1,
      payout: 800,
      multiply: 0,
      win_amount: 160,
      active_icon: [1, 2, 3, 4, 5, 6, 7, 8],
    }],
    dropLine: [],
    multiplyCount: 5,
    payout: 4000,
  },
  // SUPERWIN
  {
    icons: ['Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7'],
    activeIcons: [1, 2, 3, 4, 5, 6, 7],
    activeLines: [{
      index: 0,
      name: 'Symbol_2',
      combine: 7,
      way_243: 1,
      payout: 160,
      multiply: 0,
      win_amount: 32,
      active_icon: [1, 2, 3, 4, 5, 6, 7],
    }],
    dropLine: [],
    multiplyCount: 4,
    payout: 640,
  },
  {
    icons: ['Symbol_7', 'Symbol_7', 'Symbol_7', 'Symbol_7', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4'],
    activeIcons: [1, 2, 3, 4, 5],
    activeLines: [{
      index: 0,
      name: 'Symbol_7',
      combine: 5,
      way_243: 1,
      payout: 5,
      multiply: 0,
      win_amount: 1,
      active_icon: [1, 2, 3, 4, 5],
    }],
    dropLine: [],
    multiplyCount: 2,
    payout: 10,
  },
  {
    icons: ['Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_9', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4'],
    activeIcons: [1, 2, 3, 4, 5, 6],
    activeLines: [{
      index: 0,
      name: 'Symbol_8',
      combine: 6,
      way_243: 1,
      payout: 16,
      multiply: 0,
      win_amount: 3.2,
      active_icon: [1, 2, 3, 4, 5, 6],
    }],
    dropLine: [],
    multiplyCount: 3,
    payout: 48,
  },
  {
    icons: ['Symbol_9', 'Symbol_9', 'Symbol_9', 'Symbol_9', 'Symbol_9', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6'],
    activeIcons: [1, 2, 3, 4, 5],
    activeLines: [{
      index: 0,
      name: 'Symbol_9',
      combine: 5,
      way_243: 1,
      payout: 4,
      multiply: 0,
      win_amount: 0.8,
      active_icon: [1, 2, 3, 4, 5],
    }],
    dropLine: [],
    multiplyCount: 2,
    payout: 8,
  },
];

const PREDEFINED_LOSSES: PredefinedResult[] = [
  { icons: ['Symbol_6', 'Symbol_3', 'Symbol_8', 'Symbol_2', 'Symbol_5', 'Symbol_7', 'Symbol_4', 'Symbol_9', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_7', 'Symbol_4', 'Symbol_9', 'Symbol_3', 'Symbol_6', 'Symbol_8', 'Symbol_2', 'Symbol_0', 'Symbol_1', 'Symbol_5', 'Symbol_3', 'Symbol_4'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_8', 'Symbol_5', 'Symbol_0', 'Symbol_4', 'Symbol_7', 'Symbol_9', 'Symbol_3', 'Symbol_1', 'Symbol_2', 'Symbol_6', 'Symbol_4', 'Symbol_5'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_9', 'Symbol_6', 'Symbol_1', 'Symbol_5', 'Symbol_8', 'Symbol_0', 'Symbol_4', 'Symbol_2', 'Symbol_3', 'Symbol_7', 'Symbol_5', 'Symbol_6'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_0', 'Symbol_7', 'Symbol_2', 'Symbol_6', 'Symbol_9', 'Symbol_1', 'Symbol_5', 'Symbol_3', 'Symbol_4', 'Symbol_8', 'Symbol_6', 'Symbol_7'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_1', 'Symbol_8', 'Symbol_3', 'Symbol_7', 'Symbol_0', 'Symbol_2', 'Symbol_6', 'Symbol_4', 'Symbol_5', 'Symbol_9', 'Symbol_7', 'Symbol_8'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_2', 'Symbol_9', 'Symbol_4', 'Symbol_8', 'Symbol_1', 'Symbol_3', 'Symbol_7', 'Symbol_5', 'Symbol_6', 'Symbol_0', 'Symbol_8', 'Symbol_9'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_3', 'Symbol_0', 'Symbol_5', 'Symbol_9', 'Symbol_2', 'Symbol_4', 'Symbol_8', 'Symbol_6', 'Symbol_7', 'Symbol_1', 'Symbol_9', 'Symbol_0'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_4', 'Symbol_1', 'Symbol_6', 'Symbol_0', 'Symbol_3', 'Symbol_5', 'Symbol_9', 'Symbol_7', 'Symbol_8', 'Symbol_2', 'Symbol_0', 'Symbol_1'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_5', 'Symbol_2', 'Symbol_7', 'Symbol_1', 'Symbol_4', 'Symbol_6', 'Symbol_0', 'Symbol_8', 'Symbol_9', 'Symbol_3', 'Symbol_1', 'Symbol_2'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_6', 'Symbol_3', 'Symbol_8', 'Symbol_2', 'Symbol_5', 'Symbol_7', 'Symbol_1', 'Symbol_9', 'Symbol_0', 'Symbol_4', 'Symbol_2', 'Symbol_3'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_7', 'Symbol_4', 'Symbol_9', 'Symbol_3', 'Symbol_6', 'Symbol_8', 'Symbol_2', 'Symbol_0', 'Symbol_1', 'Symbol_5', 'Symbol_3', 'Symbol_4'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_8', 'Symbol_5', 'Symbol_0', 'Symbol_4', 'Symbol_7', 'Symbol_9', 'Symbol_3', 'Symbol_1', 'Symbol_2', 'Symbol_6', 'Symbol_4', 'Symbol_5'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_9', 'Symbol_6', 'Symbol_1', 'Symbol_5', 'Symbol_8', 'Symbol_0', 'Symbol_4', 'Symbol_2', 'Symbol_3', 'Symbol_7', 'Symbol_5', 'Symbol_6'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_0', 'Symbol_7', 'Symbol_2', 'Symbol_6', 'Symbol_9', 'Symbol_1', 'Symbol_5', 'Symbol_3', 'Symbol_4', 'Symbol_8', 'Symbol_6', 'Symbol_7'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
];

export const JACK_FROST_CONFIG: GameConfig = {
  gameId: 'jackfrost',
  gameName: "Jack Frost's Winter",
  rows: 4,
  cols: 3,
  symbols: SYMBOLS,
  paylines: PAYLINES,
  baseRtp: 96.5,
  volatility: 'high',
  winChance: 35,
  loseChance: 65,
  predefinedWins: PREDEFINED_WINS,
  predefinedLosses: PREDEFINED_LOSSES,
  minBet: 1.00,
  maxBet: 500,
  defaultBet: 1.00,
  betSizes: [1.00, 10, 100, 500],
  numLines: 10,
  hasFreeSpin: true,
  hasBonusGame: true,
  hasJackpot: false,
  jackpots: {
    mini: 500,
    minor: 2500,
    major: 12500,
    grand: 250000,
  },
};

export { SYMBOLS as JACK_FROST_SYMBOLS };
export { PAYLINES as JACK_FROST_PAYLINES };
export { PREDEFINED_WINS as JACK_FROST_WINS };
export { PREDEFINED_LOSSES as JACK_FROST_LOSSES };
