import { GameConfig, PredefinedResult, SymbolConfig, PaylineConfig } from '../../engine/types';

/**
 * Configuração do Queen of Bounty
 * Grid: 6x5, MegaWays (até 117649 ways)
 * Tema: Rainha Pirata / Tesouro
 */

const SYMBOLS: SymbolConfig[] = [
  {
    id: 0,
    name: 'Symbol_0',
    displayName: 'Wild/Queen',
    isWild: true,
    isScatter: false,
    payouts: [0, 0, 50, 100, 300, 1000],
  },
  {
    id: 1,
    name: 'Symbol_1',
    displayName: 'Scatter/Ship',
    isWild: false,
    isScatter: true,
    payouts: [0, 0, 5, 10, 30, 100],
  },
  {
    id: 2,
    name: 'Symbol_2',
    displayName: 'Red Violet Flower',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 25, 50, 150, 500],
  },
  {
    id: 3,
    name: 'Symbol_3',
    displayName: 'Purple Flower',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 20, 40, 120, 400],
  },
  {
    id: 4,
    name: 'Symbol_4',
    displayName: 'Pink Flower',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 15, 30, 90, 300],
  },
  {
    id: 5,
    name: 'Symbol_5',
    displayName: 'Grass Flower',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 10, 20, 60, 200],
  },
  {
    id: 6,
    name: 'Symbol_6',
    displayName: 'Red Mask',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 8, 16, 48, 160],
  },
  {
    id: 7,
    name: 'Symbol_7',
    displayName: 'Brown Mask',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 6, 12, 36, 120],
  },
  {
    id: 8,
    name: 'Symbol_8',
    displayName: 'A',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 4, 8, 24, 80],
  },
  {
    id: 9,
    name: 'Symbol_9',
    displayName: 'K',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 4, 8, 24, 80],
  },
  {
    id: 10,
    name: 'Symbol_10',
    displayName: 'Q',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 3, 6, 18, 60],
  },
  {
    id: 11,
    name: 'Symbol_11',
    displayName: 'J',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 3, 6, 18, 60],
  },
  {
    id: 12,
    name: 'Symbol_12',
    displayName: '10',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 2, 4, 12, 40],
  },
];

// MegaWays - posições para grid 6x5
const PAYLINES: PaylineConfig[] = [
  { id: 0, name: 'Line 1', positions: [0, 1, 2, 3, 4, 5] },
  { id: 1, name: 'Line 2', positions: [6, 7, 8, 9, 10, 11] },
  { id: 2, name: 'Line 3', positions: [12, 13, 14, 15, 16, 17] },
  { id: 3, name: 'Line 4', positions: [18, 19, 20, 21, 22, 23] },
  { id: 4, name: 'Line 5', positions: [24, 25, 26, 27, 28, 29] },
];

const PREDEFINED_WINS: PredefinedResult[] = [
  {
    icons: ['Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_5', 'Symbol_6', 'Symbol_3', 'Symbol_4', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_1', 'Symbol_0', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5'],
    activeIcons: [1, 2, 3, 4],
    activeLines: [{
      index: 0,
      name: 'Symbol_2',
      combine: 4,
      way_243: 1,
      payout: 50,
      multiply: 0,
      win_amount: 10,
      active_icon: [1, 2, 3, 4],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 50,
  },
  {
    icons: ['Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_2', 'Symbol_5', 'Symbol_1', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1'],
    activeIcons: [7, 8, 9, 10, 11],
    activeLines: [{
      index: 1,
      name: 'Symbol_3',
      combine: 5,
      way_243: 1,
      payout: 120,
      multiply: 0,
      win_amount: 24,
      active_icon: [7, 8, 9, 10, 11],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 120,
  },
  {
    icons: ['Symbol_4', 'Symbol_4', 'Symbol_4', 'Symbol_4', 'Symbol_4', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5'],
    activeIcons: [1, 2, 3, 4, 5, 6],
    activeLines: [{
      index: 0,
      name: 'Symbol_4',
      combine: 6,
      way_243: 1,
      payout: 300,
      multiply: 0,
      win_amount: 60,
      active_icon: [1, 2, 3, 4, 5, 6],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 300,
  },
  {
    icons: ['Symbol_5', 'Symbol_5', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7'],
    activeIcons: [1, 2, 3],
    activeLines: [{
      index: 0,
      name: 'Symbol_5',
      combine: 3,
      way_243: 1,
      payout: 10,
      multiply: 0,
      win_amount: 2,
      active_icon: [1, 2, 3],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 10,
  },
  // MEGAWIN
  {
    icons: ['Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6'],
    activeIcons: [1, 2, 3, 4, 5, 6],
    activeLines: [{
      index: 0,
      name: 'Symbol_0',
      combine: 6,
      way_243: 1,
      payout: 1000,
      multiply: 0,
      win_amount: 200,
      active_icon: [1, 2, 3, 4, 5, 6],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 1000,
  },
  // SUPERWIN
  {
    icons: ['Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6'],
    activeIcons: [1, 2, 3, 4, 5, 6],
    activeLines: [{
      index: 0,
      name: 'Symbol_2',
      combine: 6,
      way_243: 1,
      payout: 500,
      multiply: 0,
      win_amount: 100,
      active_icon: [1, 2, 3, 4, 5, 6],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 500,
  },
  {
    icons: ['Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_7', 'Symbol_6', 'Symbol_9', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10'],
    activeIcons: [1, 2, 3, 4],
    activeLines: [{
      index: 0,
      name: 'Symbol_8',
      combine: 4,
      way_243: 1,
      payout: 8,
      multiply: 0,
      win_amount: 1.6,
      active_icon: [1, 2, 3, 4],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 8,
  },
  {
    icons: ['Symbol_9', 'Symbol_9', 'Symbol_9', 'Symbol_8', 'Symbol_7', 'Symbol_6', 'Symbol_10', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_11'],
    activeIcons: [1, 2, 3],
    activeLines: [{
      index: 0,
      name: 'Symbol_9',
      combine: 3,
      way_243: 1,
      payout: 4,
      multiply: 0,
      win_amount: 0.8,
      active_icon: [1, 2, 3],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 4,
  },
  {
    icons: ['Symbol_10', 'Symbol_10', 'Symbol_10', 'Symbol_10', 'Symbol_10', 'Symbol_9', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10'],
    activeIcons: [1, 2, 3, 4, 5],
    activeLines: [{
      index: 0,
      name: 'Symbol_10',
      combine: 5,
      way_243: 1,
      payout: 18,
      multiply: 0,
      win_amount: 3.6,
      active_icon: [1, 2, 3, 4, 5],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 18,
  },
  {
    icons: ['Symbol_11', 'Symbol_11', 'Symbol_11', 'Symbol_11', 'Symbol_10', 'Symbol_9', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10'],
    activeIcons: [1, 2, 3, 4],
    activeLines: [{
      index: 0,
      name: 'Symbol_11',
      combine: 4,
      way_243: 1,
      payout: 6,
      multiply: 0,
      win_amount: 1.2,
      active_icon: [1, 2, 3, 4],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 6,
  },
];

const PREDEFINED_LOSSES: PredefinedResult[] = [
  { icons: ['Symbol_6', 'Symbol_3', 'Symbol_8', 'Symbol_2', 'Symbol_5', 'Symbol_10', 'Symbol_7', 'Symbol_4', 'Symbol_9', 'Symbol_0', 'Symbol_1', 'Symbol_11', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_12', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_7', 'Symbol_4', 'Symbol_9', 'Symbol_3', 'Symbol_6', 'Symbol_11', 'Symbol_8', 'Symbol_2', 'Symbol_0', 'Symbol_1', 'Symbol_5', 'Symbol_12', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_0', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_8', 'Symbol_5', 'Symbol_0', 'Symbol_4', 'Symbol_7', 'Symbol_12', 'Symbol_9', 'Symbol_3', 'Symbol_1', 'Symbol_2', 'Symbol_6', 'Symbol_10', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_1', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_9', 'Symbol_6', 'Symbol_1', 'Symbol_5', 'Symbol_8', 'Symbol_10', 'Symbol_0', 'Symbol_4', 'Symbol_2', 'Symbol_3', 'Symbol_7', 'Symbol_11', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_2', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_0', 'Symbol_7', 'Symbol_2', 'Symbol_6', 'Symbol_9', 'Symbol_11', 'Symbol_1', 'Symbol_5', 'Symbol_3', 'Symbol_4', 'Symbol_8', 'Symbol_12', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_3', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_1', 'Symbol_8', 'Symbol_3', 'Symbol_7', 'Symbol_0', 'Symbol_12', 'Symbol_2', 'Symbol_6', 'Symbol_4', 'Symbol_5', 'Symbol_9', 'Symbol_10', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_4', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_2', 'Symbol_9', 'Symbol_4', 'Symbol_8', 'Symbol_1', 'Symbol_10', 'Symbol_3', 'Symbol_7', 'Symbol_5', 'Symbol_6', 'Symbol_0', 'Symbol_11', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_5', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_3', 'Symbol_0', 'Symbol_5', 'Symbol_9', 'Symbol_2', 'Symbol_11', 'Symbol_4', 'Symbol_8', 'Symbol_6', 'Symbol_7', 'Symbol_1', 'Symbol_12', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_6', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_4', 'Symbol_1', 'Symbol_6', 'Symbol_0', 'Symbol_3', 'Symbol_12', 'Symbol_5', 'Symbol_9', 'Symbol_7', 'Symbol_8', 'Symbol_2', 'Symbol_10', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_7', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_5', 'Symbol_2', 'Symbol_7', 'Symbol_1', 'Symbol_4', 'Symbol_10', 'Symbol_6', 'Symbol_0', 'Symbol_8', 'Symbol_9', 'Symbol_3', 'Symbol_11', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_8', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_6', 'Symbol_3', 'Symbol_8', 'Symbol_2', 'Symbol_5', 'Symbol_11', 'Symbol_7', 'Symbol_1', 'Symbol_9', 'Symbol_0', 'Symbol_4', 'Symbol_12', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_9', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_7', 'Symbol_4', 'Symbol_9', 'Symbol_3', 'Symbol_6', 'Symbol_12', 'Symbol_8', 'Symbol_2', 'Symbol_0', 'Symbol_1', 'Symbol_5', 'Symbol_10', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_10', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_11', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_8', 'Symbol_5', 'Symbol_0', 'Symbol_4', 'Symbol_7', 'Symbol_10', 'Symbol_9', 'Symbol_3', 'Symbol_1', 'Symbol_2', 'Symbol_6', 'Symbol_11', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_11', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_12', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_9', 'Symbol_6', 'Symbol_1', 'Symbol_5', 'Symbol_8', 'Symbol_11', 'Symbol_0', 'Symbol_4', 'Symbol_2', 'Symbol_3', 'Symbol_7', 'Symbol_12', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_12', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_10', 'Symbol_7', 'Symbol_2', 'Symbol_6', 'Symbol_9', 'Symbol_12', 'Symbol_1', 'Symbol_5', 'Symbol_3', 'Symbol_4', 'Symbol_8', 'Symbol_0', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_0', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_12', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
];

export const QUEEN_OF_BOUNTY_CONFIG: GameConfig = {
  gameId: 'queenofbounty',
  gameName: 'Queen of Bounty',
  rows: 5,
  cols: 6,
  symbols: SYMBOLS,
  paylines: PAYLINES,
  baseRtp: 96.5,
  volatility: 'high',
  winChance: 35,
  loseChance: 65,
  predefinedWins: PREDEFINED_WINS,
  predefinedLosses: PREDEFINED_LOSSES,
  minBet: 0.20,
  maxBet: 100,
  defaultBet: 0.20,
  betSizes: [0.20, 2, 20, 100],
  numLines: 117649,
  hasFreeSpin: true,
  hasBonusGame: true,
  hasJackpot: false,
  jackpots: {
    mini: 100,
    minor: 500,
    major: 2500,
    grand: 50000,
  },
};

export { SYMBOLS as QUEEN_OF_BOUNTY_SYMBOLS };
export { PAYLINES as QUEEN_OF_BOUNTY_PAYLINES };
export { PREDEFINED_WINS as QUEEN_OF_BOUNTY_WINS };
export { PREDEFINED_LOSSES as QUEEN_OF_BOUNTY_LOSSES };
