import { GameConfig, PredefinedResult, SymbolConfig, PaylineConfig } from '../../engine/types';

/**
 * Configuração do Treasures of Aztec
 * Grid: 5x5 Cluster Pays
 * Tema: Civilização Asteca / Tesouros
 */

const SYMBOLS: SymbolConfig[] = [
  {
    id: 0,
    name: 'Symbol_0',
    displayName: 'Wild',
    isWild: true,
    isScatter: false,
    payouts: [0, 0, 5, 10, 25, 50, 100, 150, 250, 500, 1000],
  },
  {
    id: 1,
    name: 'Symbol_1',
    displayName: 'Scatter',
    isWild: false,
    isScatter: true,
    payouts: [0, 0, 3, 5, 10, 20, 30, 40, 50, 75, 100],
  },
  {
    id: 2,
    name: 'Symbol_2',
    displayName: 'Aztec King',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 4, 8, 20, 40, 80, 120, 200, 400, 800],
  },
  {
    id: 3,
    name: 'Symbol_3',
    displayName: 'Jaguar',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 3, 6, 15, 30, 60, 100, 150, 300, 600],
  },
  {
    id: 4,
    name: 'Symbol_4',
    displayName: 'Eagle',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 2, 5, 12, 25, 50, 80, 120, 250, 500],
  },
  {
    id: 5,
    name: 'Symbol_5',
    displayName: 'Sun Stone',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 2, 4, 10, 20, 40, 60, 100, 200, 400],
  },
  {
    id: 6,
    name: 'Symbol_6',
    displayName: 'Gold Mask',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 1, 3, 8, 15, 30, 50, 75, 150, 300],
  },
  {
    id: 7,
    name: 'Symbol_7',
    displayName: 'Pyramid',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 1, 2, 6, 12, 25, 40, 60, 120, 250],
  },
  {
    id: 8,
    name: 'Symbol_8',
    displayName: 'Feathered Serpent',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 1, 2, 5, 10, 20, 35, 50, 100, 200],
  },
  {
    id: 9,
    name: 'Symbol_9',
    displayName: 'Emerald',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 1, 4, 8, 16, 28, 40, 80, 160],
  },
  {
    id: 10,
    name: 'Symbol_10',
    displayName: 'Ruby',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 1, 3, 6, 12, 22, 32, 64, 128],
  },
  {
    id: 11,
    name: 'Symbol_11',
    displayName: 'Sapphire',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 1, 2, 5, 10, 18, 26, 52, 104],
  },
];

// Cluster Pays - pagamento por clusters de 5+ símbolos adjacentes
const PAYLINES: PaylineConfig[] = [
  // Cluster definitions for 5x5 grid - clusters are groups of adjacent symbols
  { id: 0, name: 'Cluster 5+', positions: [0, 1, 2, 3, 4] },
  { id: 1, name: 'Cluster Row 2', positions: [5, 6, 7, 8, 9] },
  { id: 2, name: 'Cluster Row 3', positions: [10, 11, 12, 13, 14] },
  { id: 3, name: 'Cluster Row 4', positions: [15, 16, 17, 18, 19] },
  { id: 4, name: 'Cluster Row 5', positions: [20, 21, 22, 23, 24] },
  { id: 5, name: 'Cluster Col 1', positions: [0, 5, 10, 15, 20] },
  { id: 6, name: 'Cluster Col 2', positions: [1, 6, 11, 16, 21] },
  { id: 7, name: 'Cluster Col 3', positions: [2, 7, 12, 17, 22] },
  { id: 8, name: 'Cluster Col 4', positions: [3, 8, 13, 18, 23] },
  { id: 9, name: 'Cluster Col 5', positions: [4, 9, 14, 19, 24] },
  { id: 10, name: 'Cluster Cross', positions: [2, 7, 10, 11, 12, 13, 14, 17, 22] },
  { id: 11, name: 'Cluster Square TL', positions: [0, 1, 5, 6] },
  { id: 12, name: 'Cluster Square TR', positions: [3, 4, 8, 9] },
  { id: 13, name: 'Cluster Square BL', positions: [15, 16, 20, 21] },
  { id: 14, name: 'Cluster Square BR', positions: [18, 19, 23, 24] },
  { id: 15, name: 'Cluster Center', positions: [6, 7, 8, 11, 12, 13, 16, 17, 18] },
];

const PREDEFINED_WINS: PredefinedResult[] = [
  // Cluster win with 5 matching symbols
  {
    icons: [
      'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_7', 'Symbol_8',
      'Symbol_2', 'Symbol_2', 'Symbol_9', 'Symbol_10', 'Symbol_11',
      'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7',
      'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5',
    ],
    activeIcons: [1, 2, 3, 6, 7],
    activeLines: [{
      index: 0,
      name: 'Symbol_2',
      combine: 5,
      way_243: 0,
      payout: 20,
      multiply: 0,
      win_amount: 4,
      active_icon: [1, 2, 3, 6, 7],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 20,
  },
  // Larger cluster win
  {
    icons: [
      'Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_7', 'Symbol_8',
      'Symbol_3', 'Symbol_3', 'Symbol_3', 'Symbol_10', 'Symbol_11',
      'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7',
      'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5',
    ],
    activeIcons: [1, 2, 3, 6, 7, 8, 11],
    activeLines: [{
      index: 0,
      name: 'Symbol_3',
      combine: 7,
      way_243: 0,
      payout: 100,
      multiply: 0,
      win_amount: 20,
      active_icon: [1, 2, 3, 6, 7, 8, 11],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 100,
  },
  // Small cluster
  {
    icons: [
      'Symbol_5', 'Symbol_5', 'Symbol_7', 'Symbol_8', 'Symbol_9',
      'Symbol_5', 'Symbol_5', 'Symbol_5', 'Symbol_10', 'Symbol_11',
      'Symbol_3', 'Symbol_4', 'Symbol_6', 'Symbol_6', 'Symbol_7',
      'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5',
    ],
    activeIcons: [1, 2, 6, 7, 8],
    activeLines: [{
      index: 0,
      name: 'Symbol_5',
      combine: 5,
      way_243: 0,
      payout: 20,
      multiply: 0,
      win_amount: 4,
      active_icon: [1, 2, 6, 7, 8],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 20,
  },
  // MEGAWIN - Large cluster with wild
  {
    icons: [
      'Symbol_0', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_8',
      'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_11',
      'Symbol_2', 'Symbol_2', 'Symbol_2', 'Symbol_6', 'Symbol_7',
      'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5',
    ],
    activeIcons: [1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13],
    activeLines: [{
      index: 0,
      name: 'Symbol_2',
      combine: 11,
      way_243: 0,
      payout: 800,
      multiply: 0,
      win_amount: 160,
      active_icon: [1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 800,
  },
  {
    icons: [
      'Symbol_6', 'Symbol_6', 'Symbol_6', 'Symbol_7', 'Symbol_8',
      'Symbol_6', 'Symbol_6', 'Symbol_9', 'Symbol_10', 'Symbol_11',
      'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_0', 'Symbol_7',
      'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5',
    ],
    activeIcons: [1, 2, 3, 6, 7],
    activeLines: [{
      index: 0,
      name: 'Symbol_6',
      combine: 5,
      way_243: 0,
      payout: 8,
      multiply: 0,
      win_amount: 1.6,
      active_icon: [1, 2, 3, 6, 7],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 8,
  },
  {
    icons: [
      'Symbol_4', 'Symbol_4', 'Symbol_7', 'Symbol_8', 'Symbol_9',
      'Symbol_4', 'Symbol_4', 'Symbol_4', 'Symbol_10', 'Symbol_11',
      'Symbol_4', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7',
      'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5',
    ],
    activeIcons: [1, 2, 6, 7, 8, 11, 12],
    activeLines: [{
      index: 0,
      name: 'Symbol_4',
      combine: 7,
      way_243: 0,
      payout: 80,
      multiply: 0,
      win_amount: 16,
      active_icon: [1, 2, 6, 7, 8, 11, 12],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 80,
  },
  {
    icons: [
      'Symbol_7', 'Symbol_7', 'Symbol_7', 'Symbol_8', 'Symbol_9',
      'Symbol_7', 'Symbol_7', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_1',
      'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5',
    ],
    activeIcons: [1, 2, 3, 6, 7],
    activeLines: [{
      index: 0,
      name: 'Symbol_7',
      combine: 5,
      way_243: 0,
      payout: 6,
      multiply: 0,
      win_amount: 1.2,
      active_icon: [1, 2, 3, 6, 7],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 6,
  },
  {
    icons: [
      'Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_9',
      'Symbol_8', 'Symbol_8', 'Symbol_8', 'Symbol_11', 'Symbol_0',
      'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_1',
      'Symbol_7', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0',
      'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5',
    ],
    activeIcons: [1, 2, 3, 4, 6, 7, 8],
    activeLines: [{
      index: 0,
      name: 'Symbol_8',
      combine: 7,
      way_243: 0,
      payout: 35,
      multiply: 0,
      win_amount: 7,
      active_icon: [1, 2, 3, 4, 6, 7, 8],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 35,
  },
  // Full screen bonus
  {
    icons: [
      'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0',
      'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0',
      'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0',
      'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0',
      'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0', 'Symbol_0',
    ],
    activeIcons: Array.from({ length: 25 }, (_, i) => i + 1),
    activeLines: [{
      index: 0,
      name: 'Symbol_0',
      combine: 25,
      way_243: 0,
      payout: 1000,
      multiply: 10,
      win_amount: 2000,
      active_icon: Array.from({ length: 25 }, (_, i) => i + 1),
    }],
    dropLine: [],
    multiplyCount: 10,
    payout: 10000,
  },
];

const PREDEFINED_LOSSES: PredefinedResult[] = [
  { icons: ['Symbol_7', 'Symbol_3', 'Symbol_9', 'Symbol_2', 'Symbol_5', 'Symbol_8', 'Symbol_4', 'Symbol_6', 'Symbol_11', 'Symbol_10', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_8', 'Symbol_5', 'Symbol_10', 'Symbol_3', 'Symbol_6', 'Symbol_9', 'Symbol_2', 'Symbol_7', 'Symbol_0', 'Symbol_11', 'Symbol_1', 'Symbol_4', 'Symbol_3', 'Symbol_5', 'Symbol_2', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_9', 'Symbol_6', 'Symbol_11', 'Symbol_4', 'Symbol_7', 'Symbol_10', 'Symbol_3', 'Symbol_8', 'Symbol_1', 'Symbol_0', 'Symbol_2', 'Symbol_5', 'Symbol_4', 'Symbol_6', 'Symbol_3', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_10', 'Symbol_7', 'Symbol_0', 'Symbol_5', 'Symbol_8', 'Symbol_11', 'Symbol_4', 'Symbol_9', 'Symbol_2', 'Symbol_1', 'Symbol_3', 'Symbol_6', 'Symbol_5', 'Symbol_7', 'Symbol_4', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_11', 'Symbol_8', 'Symbol_1', 'Symbol_6', 'Symbol_9', 'Symbol_0', 'Symbol_5', 'Symbol_10', 'Symbol_3', 'Symbol_2', 'Symbol_4', 'Symbol_7', 'Symbol_6', 'Symbol_8', 'Symbol_5', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_0', 'Symbol_9', 'Symbol_2', 'Symbol_7', 'Symbol_10', 'Symbol_1', 'Symbol_6', 'Symbol_11', 'Symbol_4', 'Symbol_3', 'Symbol_5', 'Symbol_8', 'Symbol_7', 'Symbol_9', 'Symbol_6', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_1', 'Symbol_10', 'Symbol_3', 'Symbol_8', 'Symbol_11', 'Symbol_2', 'Symbol_7', 'Symbol_0', 'Symbol_5', 'Symbol_4', 'Symbol_6', 'Symbol_9', 'Symbol_8', 'Symbol_10', 'Symbol_7', 'Symbol_11', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_2', 'Symbol_11', 'Symbol_4', 'Symbol_9', 'Symbol_0', 'Symbol_3', 'Symbol_8', 'Symbol_1', 'Symbol_6', 'Symbol_5', 'Symbol_7', 'Symbol_10', 'Symbol_9', 'Symbol_11', 'Symbol_8', 'Symbol_0', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_3', 'Symbol_0', 'Symbol_5', 'Symbol_10', 'Symbol_1', 'Symbol_4', 'Symbol_9', 'Symbol_2', 'Symbol_7', 'Symbol_6', 'Symbol_8', 'Symbol_11', 'Symbol_10', 'Symbol_0', 'Symbol_9', 'Symbol_1', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_4', 'Symbol_1', 'Symbol_6', 'Symbol_11', 'Symbol_2', 'Symbol_5', 'Symbol_10', 'Symbol_3', 'Symbol_8', 'Symbol_7', 'Symbol_9', 'Symbol_0', 'Symbol_11', 'Symbol_1', 'Symbol_10', 'Symbol_2', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_5', 'Symbol_2', 'Symbol_7', 'Symbol_0', 'Symbol_3', 'Symbol_6', 'Symbol_11', 'Symbol_4', 'Symbol_9', 'Symbol_8', 'Symbol_10', 'Symbol_1', 'Symbol_0', 'Symbol_2', 'Symbol_11', 'Symbol_3', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['Symbol_6', 'Symbol_3', 'Symbol_8', 'Symbol_1', 'Symbol_4', 'Symbol_7', 'Symbol_0', 'Symbol_5', 'Symbol_10', 'Symbol_9', 'Symbol_11', 'Symbol_2', 'Symbol_1', 'Symbol_3', 'Symbol_0', 'Symbol_4', 'Symbol_5', 'Symbol_6', 'Symbol_7', 'Symbol_8', 'Symbol_9', 'Symbol_10', 'Symbol_11', 'Symbol_0', 'Symbol_1'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
];

export const TREASURES_OF_AZTEC_CONFIG: GameConfig = {
  gameId: 'treasuresofaztec',
  gameName: 'Treasures of Aztec',
  rows: 5,
  cols: 5,
  symbols: SYMBOLS,
  paylines: PAYLINES,
  baseRtp: 96.7,
  volatility: 'high',
  winChance: 32,
  loseChance: 68,
  predefinedWins: PREDEFINED_WINS,
  predefinedLosses: PREDEFINED_LOSSES,
  minBet: 0.50,
  maxBet: 250,
  defaultBet: 0.50,
  betSizes: [0.50, 5, 50, 250],
  numLines: 16,
  hasFreeSpin: true,
  hasBonusGame: true,
  hasJackpot: true,
  jackpots: {
    mini: 500,
    minor: 2500,
    major: 12500,
    grand: 250000,
  },
};

export { SYMBOLS as TREASURES_OF_AZTEC_SYMBOLS };
export { PAYLINES as TREASURES_OF_AZTEC_PAYLINES };
export { PREDEFINED_WINS as TREASURES_OF_AZTEC_WINS };
export { PREDEFINED_LOSSES as TREASURES_OF_AZTEC_LOSSES };
