import { GameConfig, PredefinedResult, SymbolConfig, PaylineConfig } from '../../engine/types';

/**
 * Configuração do Treasures of Aztec
 * Grid: 5x5 Cluster Pays
 * Tema: Civilização Asteca / Tesouros
 * 
 * IMPORTANTE: Os nomes dos símbolos DEVEM corresponder exatamente ao que
 * o frontend espera: goldmask, redviolet, redmask, purple, flower, grass, a, k, q, j, 10, wild, scatter
 */

const SYMBOLS: SymbolConfig[] = [
  {
    id: 0,
    name: 'wild',
    displayName: 'Wild',
    isWild: true,
    isScatter: false,
    payouts: [0, 0, 5, 10, 25, 50, 100, 150, 250, 500, 1000],
  },
  {
    id: 1,
    name: 'scatter',
    displayName: 'Scatter',
    isWild: false,
    isScatter: true,
    payouts: [0, 0, 3, 5, 10, 20, 30, 40, 50, 75, 100],
  },
  {
    id: 2,
    name: 'goldmask',
    displayName: 'Gold Mask',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 4, 8, 20, 40, 80, 120, 200, 400, 800],
  },
  {
    id: 3,
    name: 'redviolet',
    displayName: 'Red Violet',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 3, 6, 15, 30, 60, 100, 150, 300, 600],
  },
  {
    id: 4,
    name: 'redmask',
    displayName: 'Red Mask',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 2, 5, 12, 25, 50, 80, 120, 250, 500],
  },
  {
    id: 5,
    name: 'purple',
    displayName: 'Purple',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 2, 4, 10, 20, 40, 60, 100, 200, 400],
  },
  {
    id: 6,
    name: 'flower',
    displayName: 'Flower',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 1, 3, 8, 15, 30, 50, 75, 150, 300],
  },
  {
    id: 7,
    name: 'grass',
    displayName: 'Grass',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 1, 2, 6, 12, 25, 40, 60, 120, 250],
  },
  {
    id: 8,
    name: 'a',
    displayName: 'A',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 1, 2, 5, 10, 20, 35, 50, 100, 200],
  },
  {
    id: 9,
    name: 'k',
    displayName: 'K',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 1, 4, 8, 16, 28, 40, 80, 160],
  },
  {
    id: 10,
    name: 'q',
    displayName: 'Q',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 1, 3, 6, 12, 22, 32, 64, 128],
  },
  {
    id: 11,
    name: 'j',
    displayName: 'J',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 1, 2, 5, 10, 18, 26, 52, 104],
  },
  {
    id: 12,
    name: '10',
    displayName: '10',
    isWild: false,
    isScatter: false,
    payouts: [0, 0, 0, 1, 2, 4, 8, 14, 20, 40, 80],
  },
];

// Cluster Pays - pagamento por clusters de 5+ símbolos adjacentes
const PAYLINES: PaylineConfig[] = [
  // Cluster definitions for 5x5 grid - clusters are groups of adjacent symbols
  { id: 0, name: 'Cluster 5+', positions: [0, 1, 2, 3, 4] },
  { id: 1, name: 'Cluster Row 2', positions: [5, 6, 7, 8, 9] },
  { id: 2, name: 'Cluster Row 3', positions: [10, 11, 12, 13, 14] },
  { id: 3, name: 'Cluster Row 4', positions: [15, 16, 17, 18, 19] },
  { id: 4, name: 'Cluster Row 5', positions: [20, 21, 22, 23, 24] },
  { id: 5, name: 'Cluster Col 1', positions: [0, 5, 10, 15, 20] },
  { id: 6, name: 'Cluster Col 2', positions: [1, 6, 11, 16, 21] },
  { id: 7, name: 'Cluster Col 3', positions: [2, 7, 12, 17, 22] },
  { id: 8, name: 'Cluster Col 4', positions: [3, 8, 13, 18, 23] },
  { id: 9, name: 'Cluster Col 5', positions: [4, 9, 14, 19, 24] },
  { id: 10, name: 'Cluster Cross', positions: [2, 7, 10, 11, 12, 13, 14, 17, 22] },
  { id: 11, name: 'Cluster Square TL', positions: [0, 1, 5, 6] },
  { id: 12, name: 'Cluster Square TR', positions: [3, 4, 8, 9] },
  { id: 13, name: 'Cluster Square BL', positions: [15, 16, 20, 21] },
  { id: 14, name: 'Cluster Square BR', positions: [18, 19, 23, 24] },
  { id: 15, name: 'Cluster Center', positions: [6, 7, 8, 11, 12, 13, 16, 17, 18] },
];

const PREDEFINED_WINS: PredefinedResult[] = [
  // Cluster win with 5 matching symbols
  {
    icons: [
      'goldmask', 'goldmask', 'goldmask', 'grass', 'a',
      'goldmask', 'goldmask', 'k', 'q', 'j',
      'redviolet', 'redmask', 'purple', 'flower', 'grass',
      'a', 'k', 'q', 'j', 'wild',
      'scatter', 'goldmask', 'redviolet', 'redmask', 'purple',
    ],
    activeIcons: [1, 2, 3, 6, 7],
    activeLines: [{
      index: 0,
      name: 'goldmask',
      combine: 5,
      way_243: 0,
      payout: 20,
      multiply: 0,
      win_amount: 4,
      active_icon: [1, 2, 3, 6, 7],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 20,
  },
  // Larger cluster win
  {
    icons: [
      'redviolet', 'redviolet', 'redviolet', 'grass', 'a',
      'redviolet', 'redviolet', 'redviolet', 'q', 'j',
      'redviolet', 'redmask', 'purple', 'flower', 'grass',
      'a', 'k', 'q', 'j', 'wild',
      'scatter', 'goldmask', 'redviolet', 'redmask', 'purple',
    ],
    activeIcons: [1, 2, 3, 6, 7, 8, 11],
    activeLines: [{
      index: 0,
      name: 'redviolet',
      combine: 7,
      way_243: 0,
      payout: 100,
      multiply: 0,
      win_amount: 20,
      active_icon: [1, 2, 3, 6, 7, 8, 11],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 100,
  },
  // Small cluster
  {
    icons: [
      'purple', 'purple', 'grass', 'a', 'k',
      'purple', 'purple', 'purple', 'q', 'j',
      'redviolet', 'redmask', 'flower', 'flower', 'grass',
      'a', 'k', 'q', 'j', 'wild',
      'scatter', 'goldmask', 'redviolet', 'redmask', 'purple',
    ],
    activeIcons: [1, 2, 6, 7, 8],
    activeLines: [{
      index: 0,
      name: 'purple',
      combine: 5,
      way_243: 0,
      payout: 20,
      multiply: 0,
      win_amount: 4,
      active_icon: [1, 2, 6, 7, 8],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 20,
  },
  // MEGAWIN - Large cluster with wild
  {
    icons: [
      'wild', 'goldmask', 'goldmask', 'goldmask', 'a',
      'goldmask', 'goldmask', 'goldmask', 'goldmask', 'j',
      'goldmask', 'goldmask', 'goldmask', 'flower', 'grass',
      'a', 'k', 'q', 'j', 'wild',
      'scatter', 'goldmask', 'redviolet', 'redmask', 'purple',
    ],
    activeIcons: [1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13],
    activeLines: [{
      index: 0,
      name: 'goldmask',
      combine: 11,
      way_243: 0,
      payout: 800,
      multiply: 0,
      win_amount: 160,
      active_icon: [1, 2, 3, 4, 6, 7, 8, 9, 11, 12, 13],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 800,
  },
  {
    icons: [
      'flower', 'flower', 'flower', 'grass', 'a',
      'flower', 'flower', 'k', 'q', 'j',
      'redviolet', 'redmask', 'purple', 'wild', 'grass',
      'a', 'k', 'q', 'j', 'wild',
      'scatter', 'goldmask', 'redviolet', 'redmask', 'purple',
    ],
    activeIcons: [1, 2, 3, 6, 7],
    activeLines: [{
      index: 0,
      name: 'flower',
      combine: 5,
      way_243: 0,
      payout: 8,
      multiply: 0,
      win_amount: 1.6,
      active_icon: [1, 2, 3, 6, 7],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 8,
  },
  {
    icons: [
      'redmask', 'redmask', 'grass', 'a', 'k',
      'redmask', 'redmask', 'redmask', 'q', 'j',
      'redmask', 'redmask', 'purple', 'flower', 'grass',
      'a', 'k', 'q', 'j', 'wild',
      'scatter', 'goldmask', 'redviolet', 'redmask', 'purple',
    ],
    activeIcons: [1, 2, 6, 7, 8, 11, 12],
    activeLines: [{
      index: 0,
      name: 'redmask',
      combine: 7,
      way_243: 0,
      payout: 80,
      multiply: 0,
      win_amount: 16,
      active_icon: [1, 2, 6, 7, 8, 11, 12],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 80,
  },
  {
    icons: [
      'grass', 'grass', 'grass', 'a', 'k',
      'grass', 'grass', 'q', 'j', 'wild',
      'redviolet', 'redmask', 'purple', 'flower', 'scatter',
      'a', 'k', 'q', 'j', 'wild',
      'scatter', 'goldmask', 'redviolet', 'redmask', 'purple',
    ],
    activeIcons: [1, 2, 3, 6, 7],
    activeLines: [{
      index: 0,
      name: 'grass',
      combine: 5,
      way_243: 0,
      payout: 6,
      multiply: 0,
      win_amount: 1.2,
      active_icon: [1, 2, 3, 6, 7],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 6,
  },
  {
    icons: [
      'a', 'a', 'a', 'a', 'k',
      'a', 'a', 'a', 'j', 'wild',
      'redviolet', 'redmask', 'purple', 'flower', 'scatter',
      'grass', 'k', 'q', 'j', 'wild',
      'scatter', 'goldmask', 'redviolet', 'redmask', 'purple',
    ],
    activeIcons: [1, 2, 3, 4, 6, 7, 8],
    activeLines: [{
      index: 0,
      name: 'a',
      combine: 7,
      way_243: 0,
      payout: 35,
      multiply: 0,
      win_amount: 7,
      active_icon: [1, 2, 3, 4, 6, 7, 8],
    }],
    dropLine: [],
    multiplyCount: 1,
    payout: 35,
  },
  // Full screen bonus
  {
    icons: [
      'wild', 'wild', 'wild', 'wild', 'wild',
      'wild', 'wild', 'wild', 'wild', 'wild',
      'wild', 'wild', 'wild', 'wild', 'wild',
      'wild', 'wild', 'wild', 'wild', 'wild',
      'wild', 'wild', 'wild', 'wild', 'wild',
    ],
    activeIcons: Array.from({ length: 25 }, (_, i) => i + 1),
    activeLines: [{
      index: 0,
      name: 'wild',
      combine: 25,
      way_243: 0,
      payout: 1000,
      multiply: 10,
      win_amount: 2000,
      active_icon: Array.from({ length: 25 }, (_, i) => i + 1),
    }],
    dropLine: [],
    multiplyCount: 10,
    payout: 10000,
  },
];

const PREDEFINED_LOSSES: PredefinedResult[] = [
  { icons: ['grass', 'redviolet', 'k', 'goldmask', 'purple', 'a', 'redmask', 'flower', 'j', 'q', 'wild', 'scatter', 'goldmask', 'redviolet', 'redmask', 'purple', 'flower', 'grass', 'a', 'k', 'q', 'j', 'wild', 'scatter', 'goldmask'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['a', 'purple', 'q', 'redviolet', 'flower', 'k', 'goldmask', 'grass', 'wild', 'j', 'scatter', 'redmask', 'redviolet', 'purple', 'goldmask', 'flower', 'grass', 'a', 'k', 'q', 'j', 'wild', 'scatter', 'goldmask', 'redviolet'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['k', 'flower', 'j', 'redmask', 'grass', 'q', 'redviolet', 'a', 'scatter', 'wild', 'goldmask', 'purple', 'redmask', 'flower', 'redviolet', 'grass', 'a', 'k', 'q', 'j', 'wild', 'scatter', 'goldmask', 'redviolet', 'redmask'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['q', 'grass', 'wild', 'purple', 'a', 'j', 'redmask', 'k', 'goldmask', 'scatter', 'redviolet', 'flower', 'purple', 'grass', 'redmask', 'a', 'k', 'q', 'j', 'wild', 'scatter', 'goldmask', 'redviolet', 'redmask', 'purple'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['j', 'a', 'scatter', 'flower', 'k', 'wild', 'purple', 'q', 'redviolet', 'goldmask', 'redmask', 'grass', 'flower', 'a', 'purple', 'k', 'q', 'j', 'wild', 'scatter', 'goldmask', 'redviolet', 'redmask', 'purple', 'flower'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['wild', 'k', 'goldmask', 'grass', 'q', 'scatter', 'flower', 'j', 'redmask', 'redviolet', 'purple', 'a', 'grass', 'k', 'flower', 'q', 'j', 'wild', 'scatter', 'goldmask', 'redviolet', 'redmask', 'purple', 'flower', 'grass'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['scatter', 'q', 'redviolet', 'a', 'j', 'goldmask', 'grass', 'wild', 'purple', 'redmask', 'flower', 'k', 'a', 'q', 'grass', 'j', 'wild', 'scatter', 'goldmask', 'redviolet', 'redmask', 'purple', 'flower', 'grass', 'a'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['goldmask', 'j', 'redmask', 'k', 'wild', 'redviolet', 'a', 'scatter', 'flower', 'purple', 'grass', 'q', 'k', 'j', 'a', 'wild', 'scatter', 'goldmask', 'redviolet', 'redmask', 'purple', 'flower', 'grass', 'a', 'k'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['redviolet', 'wild', 'purple', 'q', 'scatter', 'redmask', 'k', 'goldmask', 'grass', 'flower', 'a', 'j', 'q', 'wild', 'k', 'scatter', 'goldmask', 'redviolet', 'redmask', 'purple', 'flower', 'grass', 'a', 'k', 'q'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['redmask', 'scatter', 'flower', 'j', 'goldmask', 'purple', 'q', 'redviolet', 'a', 'grass', 'k', 'wild', 'j', 'scatter', 'q', 'goldmask', 'redviolet', 'redmask', 'purple', 'flower', 'grass', 'a', 'k', 'q', 'j'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['purple', 'goldmask', 'grass', 'wild', 'redviolet', 'flower', 'j', 'redmask', 'k', 'a', 'q', 'scatter', 'wild', 'goldmask', 'j', 'redviolet', 'redmask', 'purple', 'flower', 'grass', 'a', 'k', 'q', 'j', 'wild'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
  { icons: ['flower', 'redviolet', 'a', 'scatter', 'redmask', 'grass', 'wild', 'purple', 'q', 'k', 'j', 'goldmask', 'scatter', 'redviolet', 'wild', 'redmask', 'purple', 'flower', 'grass', 'a', 'k', 'q', 'j', 'wild', 'scatter'], activeIcons: [], activeLines: [], dropLine: [], multiplyCount: 1, payout: 0 },
];

export const TREASURES_OF_AZTEC_CONFIG: GameConfig = {
  gameId: 'treasuresofaztec',
  gameName: 'Treasures of Aztec',
  rows: 5,
  cols: 5,
  symbols: SYMBOLS,
  paylines: PAYLINES,
  baseRtp: 96.7,
  volatility: 'high',
  winChance: 32,
  loseChance: 68,
  predefinedWins: PREDEFINED_WINS,
  predefinedLosses: PREDEFINED_LOSSES,
  minBet: 0.50,
  maxBet: 250,
  defaultBet: 0.50,
  betSizes: [0.50, 5, 50, 250],
  numLines: 16,
  useFlatIconData: true, // Treasures of Aztec usa SlotAt(index) para acessar símbolos linearmente
  hasFreeSpin: true,
  hasBonusGame: true,
  hasJackpot: true,
  jackpots: {
    mini: 500,
    minor: 2500,
    major: 12500,
    grand: 250000,
  },
};

export { SYMBOLS as TREASURES_OF_AZTEC_SYMBOLS };
export { PAYLINES as TREASURES_OF_AZTEC_PAYLINES };
export { PREDEFINED_WINS as TREASURES_OF_AZTEC_WINS };
export { PREDEFINED_LOSSES as TREASURES_OF_AZTEC_LOSSES };
